ports:
  - port: 4040 # pyspark UI
    onOpen: notify
  - port: 5555
    onOpen: ignore
  - port: 8080
    onOpen: open-browser

tasks:
  - name: Gitpod config (browser open, workspace bin path)
    init: |
      mkdir -p /workspace/bin
      cat > /workspace/bin/open.sh <<'EOF'
      #!/bin/bash
      exec gp preview --external "$@"
      EOF
      chmod +x /workspace/bin/open.sh
    command: |
      sudo update-alternatives --install /usr/bin/www-browser www-browser /workspace/bin/open.sh 100
      exit
  - name: Install conveyor
    init: curl -s https://static.conveyordata.com/cli-install/install.sh | bash
    command: |
      curl -s https://static.conveyordata.com/cli-install/update.sh | bash
      exit
  - name: setup
    init: |
      python3 -m venv venv
    command: |
      echo "source $(pwd)/venv/bin/activate" >> ~/.bashrc
      source venv/bin/activate
  - name: Pull images
    env:
      AIRFLOW_IMAGE_NAME: dmacademy/airflow:2.3.4
    init: |
      docker-compose --file ../docker-compose.yml pull
      gp sync-done pull

  - name: Boot Airflow
    env:
      AIRFLOW_IMAGE_NAME: dmacademy/airflow:2.3.4
    init: |
      gp sync-await pull
      docker-compose --file ../docker-compose.yml up airflow-init
    before: |
      mkdir -p ./mount/dags ./mount/logs ./mount/plugins
      echo -e "AIRFLOW_UID=$(id -u)" >> ../.env
      #      docker build . --tag academy-airflow:2.2.3
      #      echo -e "AIRFLOW_IMAGE_NAME=academy-airflow:2.2.3" >> ../.env
      # Make sure to add these to your gitpod variables: https://gitpod.io/variables
      # Their value can be obtained from the "terraform apply" outputs.
      echo -e "AWS_ACCESS_KEY_ID=${AIRFLOW_IAM_ACCESS_KEY}" >> ../.env
      echo -e "AWS_SECRET_ACCESS_KEY=${AIRFLOW_IAM_SECRET_ACCESS_KEY}" >> ../.env
    command: |
      docker-compose --file ../docker-compose.yml up

vscode:
  extensions:
    - ms-python.python
